services:
  backend:
    build:
      context: .
    container_name: trotamundos_api
    ports:
      - "3000:80"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: bf6fc7f9ee1a12ddca1e19359c9d8e8c
      DB_HOST: 67.205.148.136
      DB_PORT: 1433
      DB_USERNAME: sa
      DB_PASSWORD: Trota01@
      DB_NAME: Trotamundosdb
    networks:
      - trotamundos

networks:
  trotamundos:
    external: true
