default: &default
  adapter: sqlserver
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] || 1433 %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>
  encoding: utf8
  azure: false
  mode: dblib
  timeout: 50000
  login_timeout: 10

development:
  <<: *default

test:
  <<: *default

production:
  primary:
    <<: *default
  queue:
    <<: *default

cable:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
