# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[8.0].define(version: 2025_05_28_175100) do
  create_schema "Catalogos"
  create_schema "Clientes"
  create_schema "Seguridad"

  create_table "Catalogos.Estatus", primary_key: "Id_Estatus", id: :integer, force: :cascade do |t|
    t.varchar "Descripcion", limit: 255
  end

  create_table "Catalogos.Roles", primary_key: "Id_rol", id: :integer, force: :cascade do |t|
    t.varchar "Descripcion", limit: 255
    t.integer "Estatus"
  end

  create_table "ChecklistHistorico", primary_key: "Id", id: :integer, force: :cascade do |t|
    t.integer "IdChecklist"
    t.integer "IdVehiculo"
    t.integer "IdEmpleado"
    t.datetime "Fecha", precision: nil
    t.integer "TiempoTranscurrido"
    t.datetime "FechaRegistro", precision: nil, default: -> { "getdate()" }
    t.string "Estado", limit: 50, default: "Pendiente"
  end

  create_table "ChecklistHistoricoServicio", primary_key: "Id", id: :integer, force: :cascade do |t|
    t.integer "IdChecklist"
    t.integer "IdVehiculo"
    t.integer "IdEmpleado"
    t.datetime "Fecha", precision: nil
    t.integer "TiempoTranscurrido"
    t.datetime "FechaRegistro", precision: nil, default: -> { "getdate()" }
    t.string "Estado", limit: 50, default: "Pendiente"
  end

  create_table "Clientes.Cliente", primary_key: "idCliente", force: :cascade do |t|
    t.string "Nombre", limit: 500
    t.string "Calle", limit: 250
    t.string "Colonia", limit: 250
    t.string "Ciudad", limit: 250
    t.string "Estado", limit: 250
    t.string "Tel", limit: 250
    t.string "Cel", limit: 250
    t.string "Email", limit: 250
    t.string "RFC", limit: 250
    t.string "No_int", limit: 250
    t.string "Facturar_a", limit: 250
    t.integer "IdUsuarioEmpleado"
    t.integer "Activo"
  end

  create_table "Flotillas", primary_key: "IdFlotilla", id: :integer, force: :cascade do |t|
    t.string "NamesFlotillas", limit: 250
    t.string "Encargado", limit: 250
  end

  create_table "OrdenDeServicio", primary_key: "idOrden", id: :integer, force: :cascade do |t|
    t.integer "IdVehiculo"
    t.integer "IdTecnico"
    t.datetime "FechaCreacion", precision: nil
    t.integer "IdCliente"
    t.integer "IdEmpleado"
  end

  create_table "ReporteVentas", primary_key: "Id", id: :integer, force: :cascade do |t|
    t.datetime "Date", precision: nil, null: false
    t.integer "ServiceOrderId"
    t.integer "VehicleId"
    t.varchar "Credit", limit: 100, null: false
    t.varchar "InitialService", limit: 100, null: false
    t.integer "Finalized", null: false
    t.boolean "Reception", default: false, null: false
    t.boolean "Entry", default: false, null: false
    t.boolean "Repair", default: false, null: false
    t.boolean "Checklist", default: false, null: false
    t.varchar "Technician", limit: 100
    t.boolean "Quotation", default: false, null: false
    t.boolean "Authorizacion", default: false, null: false
    t.boolean "Additional", default: false, null: false
    t.boolean "Washing", default: false, null: false
    t.boolean "Delivery", default: false, null: false
    t.text_basic "Comments"
  end

  create_table "Seguridad.Usuarios", primary_key: "IdUsuario", force: :cascade do |t|
    t.text "Nombre"
    t.string "Password", limit: 250
    t.integer "Rol"
    t.integer "Estatus"
  end

  create_table "Vehiculos", primary_key: "ID", id: :integer, force: :cascade do |t|
    t.integer "Id_Cliente"
    t.integer "Id_Empleado"
    t.string "Marca", limit: 150
    t.string "Modelo", limit: 150
    t.string "Color", limit: 150
    t.string "No_serie", limit: 150
    t.string "Placa", limit: 150
    t.string "Tipo", limit: 150
    t.string "Motor", limit: 150
    t.string "Kms", limit: 150
    t.integer "Espejo_retrovisor"
    t.integer "Espejo_izquierdo"
    t.integer "Antena"
    t.integer "Tapones_ruedas"
    t.integer "Radio"
    t.integer "Encendedor"
    t.integer "Gato"
    t.integer "Herramienta"
    t.integer "Llanta_refaccion"
    t.integer "Limpiadores"
    t.integer "Pintura_rayada"
    t.integer "Cristales_rotos"
    t.integer "Golpes"
    t.integer "Tapetes"
    t.integer "Extintor"
    t.integer "Tapones_gasolina"
    t.integer "Calaveras_rotas"
    t.integer "Molduras_completas"
    t.integer "Panel_instrumentos"
    t.integer "Lado_izquierdo"
    t.integer "Lado_izquierdo_inf"
    t.integer "Lado_derecho"
    t.integer "Lado_derecho_inf"
    t.integer "Tablero"
    t.integer "Guantera"
    t.integer "Consola"
    t.text "Espejo_retrovisor_foto"
    t.text "Espejo_izquierdo_foto"
    t.text "Antena_foto"
    t.text "Tapones_ruedas_foto"
    t.text "Radio_foto"
    t.text "Encendedor_foto"
    t.text "Gato_foto"
    t.text "Herramienta_foto"
    t.text "Llanta_refaccion_foto"
    t.text "Limpiadores_foto"
    t.text "Pintura_rayada_foto"
    t.text "Cristales_rotos_foto"
    t.text "Golpes_foto"
    t.text "Tapetes_foto"
    t.text "Extintor_foto"
    t.text "Tapones_gasolina_foto"
    t.text "Calaveras_rotas_foto"
    t.text "Molduras_completas_foto"
    t.integer "Espejo_derecho"
    t.text "Espejo_derecho_foto"
    t.text "Espejo_retrovisor_video"
    t.text "Espejo_izquierdo_video"
    t.text "Antena_video"
    t.text "Tapones_ruedas_video"
    t.text "Radio_video"
    t.text "Encendedor_video"
    t.text "Gato_video"
    t.text "Herramienta_video"
    t.text "Llanta_refaccion_video"
    t.text "Limpiadores_video"
    t.text "Pintura_rayada_video"
    t.text "Cristales_rotos_video"
    t.text "Golpes_video"
    t.text "Tapetes_video"
    t.text "Extintor_video"
    t.text "Tapones_gasolina_video"
    t.text "Calaveras_rotas_video"
    t.text "Molduras_completas_video"
    t.text "Espejo_derecho_video"
    t.integer "MotorVehiculo"
    t.integer "Acumulador"
    t.text "MotorVehiculo_foto"
    t.text "Acumulador_foto"
    t.text "MotorVehiculo_video"
    t.text "Acumulador_video"
    t.integer "IdFlotilla"
    t.integer "IdOrdenServicio"
    t.text "Panel_instrumentos_foto"
    t.text "Lado_izquierdo_foto"
    t.text "Lado_izquierdo_inf_foto"
    t.text "Lado_derecho_foto"
    t.text "Lado_derecho_inf_foto"
    t.text "Tablero_foto"
    t.text "Guantera_foto"
    t.text "Consola_foto"
    t.text "Panel_instrumentos_video"
    t.text "Lado_izquierdo_video"
    t.text "Lado_izquierdo_inf_video"
    t.text "Lado_derecho_video"
    t.text "Lado_derecho_inf_video"
    t.text "Tablero_video"
    t.text "Guantera_video"
    t.text "Consola_video"
    t.integer "Activo"
  end

  create_table "checklist", id: :integer, force: :cascade do |t|
    t.date "fecha"
    t.integer "Id_empleado"
    t.integer "Id_vehiculo"
    t.integer "id_ordendeservicio"
    t.integer "lectura_codigos"
    t.text "lectura_codigos_observacion"
    t.text "lectura_codigos_foto"
    t.integer "servofreno"
    t.text "servofreno_observacion"
    t.text "servofreno_foto"
    t.integer "pedal_freno"
    t.text "pedal_freno_observacion"
    t.text "pedal_freno_foto"
    t.integer "pedal_estacionamiento"
    t.text "pedal_estacionamiento_observacion"
    t.text "pedal_estacionamiento_foto"
    t.integer "cinturon_seguridad"
    t.text "cinturon_seguridad_observacion"
    t.text "cinturon_seguridad_foto"
    t.integer "cuadro_instrumentos"
    t.text "cuadro_instrumentos_observacion"
    t.text "cuadro_instrumentos_foto"
    t.integer "aire_acondicionado"
    t.text "aire_acondicionado_observacion"
    t.text "aire_acondicionado_foto"
    t.integer "bocina_claxon"
    t.text "bocina_claxon_observacion"
    t.text "bocina_claxon_foto"
    t.integer "iluminacion_interior"
    t.text "iluminacion_interior_observacion"
    t.text "iluminacion_interior_foto"
    t.integer "iluminacion_externa"
    t.text "iluminacion_externa_observacion"
    t.text "iluminacion_externa_foto"
    t.integer "limpiaparabrisas"
    t.text "limpiaparabrisas_observacion"
    t.text "limpiaparabrisas_foto"
    t.integer "limpia_medallon"
    t.text "limpia_medallon_observacion"
    t.text "limpia_medallon_foto"
    t.integer "neumaticos_friccion"
    t.text "neumaticos_friccion_observacion"
    t.text "neumaticos_friccion_foto"
    t.integer "otros_vehiculo_en_piso"
    t.text "otros_vehiculo_en_piso_observacion"
    t.text "otros_vehiculo_en_piso_foto"
    t.integer "estado_fugas_aceite"
    t.text "estado_fugas_aceite_observacion"
    t.text "estado_fugas_aceite_foto"
    t.integer "estado_nivel_calidad_lubricante_transmision"
    t.text "estado_nivel_calidad_lubricante_transmision_observacion"
    t.text "estado_nivel_calidad_lubricante_transmision_foto"
    t.integer "estado_nivel_calidad_lubricante_diferencial"
    t.text "estado_nivel_calidad_lubricante_diferencial_observacion"
    t.text "estado_nivel_calidad_lubricante_diferencial_foto"
    t.integer "cubrepolvos_flechas"
    t.text "cubrepolvos_flechas_observacion"
    t.text "cubrepolvos_flechas_foto"
    t.integer "componentes_direccion"
    t.text "componentes_direccion_observacion"
    t.text "componentes_direccion_foto"
    t.integer "componentes_suspesion"
    t.text "componentes_suspesion_observacion"
    t.text "componentes_suspesion_foto"
    t.integer "sistema_escape_completo"
    t.text "sistema_escape_completo_observacion"
    t.text "sistema_escape_completo_foto"
    t.integer "sistema_alimentacion_combustible"
    t.text "sistema_alimentacion_combustible_observacion"
    t.text "sistema_alimentacion_combustible_foto"
    t.integer "filtro_combustible"
    t.text "filtro_combustible_observacion"
    t.text "filtro_combustible_foto"
    t.integer "control_fugas_direccion_hidraulica"
    t.text "control_fugas_direccion_hidraulica_observacion"
    t.text "control_fugas_direccion_hidraulica_foto"
    t.integer "otros_altura_total"
    t.text "otros_altura_total_observacion"
    t.text "otros_altura_total_foto"
    t.integer "rodamiento_mazas_rueda"
    t.text "rodamiento_mazas_rueda_observacion"
    t.text "rodamiento_mazas_rueda_foto"
    t.integer "holgura_partes_suspension_rueda"
    t.text "holgura_partes_suspension_rueda_observacion"
    t.text "holgura_partes_suspension_rueda_foto"
    t.integer "control_neumaticos_desgaste_presion"
    t.text "control_neumaticos_desgaste_presion_observacion"
    t.text "control_neumaticos_desgaste_presion_foto"
    t.integer "profundidad"
    t.text "profundidad_observacion"
    t.text "profundidad_foto"
    t.integer "presion"
    t.text "presion_observacion"
    t.text "presion_foto"
    t.integer "otros_altura_media"
    t.text "otros_altura_media_observacion"
    t.text "otros_altura_media_foto"
    t.integer "nivel_calidad_aceite_motor"
    t.text "nivel_calidad_aceite_motor_observacion"
    t.text "nivel_calidad_aceite_motor_foto"
    t.integer "filtro_aire"
    t.text "filtro_aire_observacion"
    t.text "filtro_aire_foto"
    t.integer "filtro_polen"
    t.text "filtro_polen_observacion"
    t.text "filtro_polen_foto"
    t.integer "filtro_pcv"
    t.text "filtro_pcv_observacion"
    t.text "filtro_pcv_foto"
    t.integer "valvula_pcv"
    t.text "valvula_pcv_observacion"
    t.text "valvula_pcv_foto"
    t.integer "bujias_encendido"
    t.text "bujias_encendido_observacion"
    t.text "bujias_encendido_foto"
    t.integer "cables_bujias_bobinas_ignicion"
    t.text "cables_bujias_bobinas_ignicion_observacion"
    t.text "cables_bujias_bobinas_ignicion_foto"
    t.integer "nivel_anticongenlante"
    t.text "nivel_anticongenlante_observacion"
    t.text "nivel_anticongenlante_foto"
    t.integer "tapon_radiador"
    t.text "tapon_radiador_observacion"
    t.text "tapon_radiador_foto"
    t.integer "mangueras_sistema"
    t.text "mangueras_sistema_observacion"
    t.text "mangueras_sistema_foto"
    t.integer "desempeño_ventilador"
    t.text "desempeño_ventilador_observacion"
    t.text "desempeño_ventilador_foto"
    t.integer "calidad_liquido_limpiaparabrisas"
    t.text "calidad_liquido_limpiaparabrisas_observacion"
    t.text "calidad_liquido_limpiaparabrisas_foto"
    t.integer "calidad_aceite_direccion_hidraulica"
    t.text "calidad_aceite_direccion_hidraulica_observacion"
    t.text "calidad_aceite_direccion_hidraulica_foto"
    t.integer "calidad_aceite_transmision_bayoneta"
    t.text "calidad_aceite_transmision_bayoneta_observacion"
    t.text "calidad_aceite_transmision_bayoneta_foto"
    t.integer "liquido_bateria_condiciones"
    t.text "liquido_bateria_condiciones_observacion"
    t.text "liquido_bateria_condiciones_foto"
    t.integer "bandas_poly_v"
    t.text "bandas_poly_v_observacion"
    t.text "bandas_poly_v_foto"
    t.integer "poleas_banda"
    t.text "poleas_banda_observacion"
    t.text "poleas_banda_foto"
    t.integer "banda_tiempo"
    t.text "banda_tiempo_observacion"
    t.text "banda_tiempo_foto"
    t.integer "otros_habitaculo_motor"
    t.text "otros_habitaculo_motor_observacion"
    t.text "otros_habitaculo_motor_foto"
    t.integer "reset_intervalo_servicio"
    t.text "reset_intervalo_servicio_observacion"
    t.text "reset_intervalo_servicio_foto"
    t.integer "ajuste_tornillos_neumaticos_torquimetro"
    t.text "ajuste_tornillos_neumaticos_torquimetro_observacion"
    t.text "ajuste_tornillos_neumaticos_torquimetro_foto"
    t.integer "limpiar_libricar_puertas_cerraduras"
    t.text "limpiar_libricar_puertas_cerraduras_observacion"
    t.text "limpiar_libricar_puertas_cerraduras_foto"
    t.integer "completar_plan_mantenimiento"
    t.text "completar_plan_mantenimiento_observacion"
    t.text "completar_plan_mantenimiento_foto"
    t.text "NumeroSerie"
    t.string "TiempoTranscurrido", limit: 50
    t.integer "Activo"
  end

  create_table "checklist_Servicio", id: :integer, force: :cascade do |t|
    t.date "fecha"
    t.integer "Id_empleado"
    t.integer "Id_vehiculo"
    t.integer "id_ordendeservicio"
    t.integer "lectura_codigos"
    t.text "lectura_codigos_observacion"
    t.text "lectura_codigos_foto"
    t.integer "servofreno"
    t.text "servofreno_observacion"
    t.text "servofreno_foto"
    t.integer "pedal_freno"
    t.text "pedal_freno_observacion"
    t.text "pedal_freno_foto"
    t.integer "pedal_estacionamiento"
    t.text "pedal_estacionamiento_observacion"
    t.text "pedal_estacionamiento_foto"
    t.integer "cinturon_seguridad"
    t.text "cinturon_seguridad_observacion"
    t.text "cinturon_seguridad_foto"
    t.integer "cuadro_instrumentos"
    t.text "cuadro_instrumentos_observacion"
    t.text "cuadro_instrumentos_foto"
    t.integer "aire_acondicionado"
    t.text "aire_acondicionado_observacion"
    t.text "aire_acondicionado_foto"
    t.integer "bocina_claxon"
    t.text "bocina_claxon_observacion"
    t.text "bocina_claxon_foto"
    t.integer "iluminacion_interior"
    t.text "iluminacion_interior_observacion"
    t.text "iluminacion_interior_foto"
    t.integer "iluminacion_externa"
    t.text "iluminacion_externa_observacion"
    t.text "iluminacion_externa_foto"
    t.integer "limpiaparabrisas"
    t.text "limpiaparabrisas_observacion"
    t.text "limpiaparabrisas_foto"
    t.integer "limpia_medallon"
    t.text "limpia_medallon_observacion"
    t.text "limpia_medallon_foto"
    t.integer "neumaticos_friccion"
    t.text "neumaticos_friccion_observacion"
    t.text "neumaticos_friccion_foto"
    t.integer "otros_vehiculo_en_piso"
    t.text "otros_vehiculo_en_piso_observacion"
    t.text "otros_vehiculo_en_piso_foto"
    t.integer "estado_fugas_aceite"
    t.text "estado_fugas_aceite_observacion"
    t.text "estado_fugas_aceite_foto"
    t.integer "estado_nivel_calidad_lubricante_transmision"
    t.text "estado_nivel_calidad_lubricante_transmision_observacion"
    t.text "estado_nivel_calidad_lubricante_transmision_foto"
    t.integer "estado_nivel_calidad_lubricante_diferencial"
    t.text "estado_nivel_calidad_lubricante_diferencial_observacion"
    t.text "estado_nivel_calidad_lubricante_diferencial_foto"
    t.integer "cubrepolvos_flechas"
    t.text "cubrepolvos_flechas_observacion"
    t.text "cubrepolvos_flechas_foto"
    t.integer "componentes_direccion"
    t.text "componentes_direccion_observacion"
    t.text "componentes_direccion_foto"
    t.integer "componentes_suspesion"
    t.text "componentes_suspesion_observacion"
    t.text "componentes_suspesion_foto"
    t.integer "sistema_escape_completo"
    t.text "sistema_escape_completo_observacion"
    t.text "sistema_escape_completo_foto"
    t.integer "sistema_alimentacion_combustible"
    t.text "sistema_alimentacion_combustible_observacion"
    t.text "sistema_alimentacion_combustible_foto"
    t.integer "filtro_combustible"
    t.text "filtro_combustible_observacion"
    t.text "filtro_combustible_foto"
    t.integer "control_fugas_direccion_hidraulica"
    t.text "control_fugas_direccion_hidraulica_observacion"
    t.text "control_fugas_direccion_hidraulica_foto"
    t.integer "otros_altura_total"
    t.text "otros_altura_total_observacion"
    t.text "otros_altura_total_foto"
    t.integer "rodamiento_mazas_rueda"
    t.text "rodamiento_mazas_rueda_observacion"
    t.text "rodamiento_mazas_rueda_foto"
    t.integer "holgura_partes_suspension_rueda"
    t.text "holgura_partes_suspension_rueda_observacion"
    t.text "holgura_partes_suspension_rueda_foto"
    t.integer "control_neumaticos_desgaste_presion"
    t.text "control_neumaticos_desgaste_presion_observacion"
    t.text "control_neumaticos_desgaste_presion_foto"
    t.integer "profundidad"
    t.text "profundidad_observacion"
    t.text "profundidad_foto"
    t.integer "presion"
    t.text "presion_observacion"
    t.text "presion_foto"
    t.integer "otros_altura_media"
    t.text "otros_altura_media_observacion"
    t.text "otros_altura_media_foto"
    t.integer "nivel_calidad_aceite_motor"
    t.text "nivel_calidad_aceite_motor_observacion"
    t.text "nivel_calidad_aceite_motor_foto"
    t.integer "filtro_aire"
    t.text "filtro_aire_observacion"
    t.text "filtro_aire_foto"
    t.integer "filtro_polen"
    t.text "filtro_polen_observacion"
    t.text "filtro_polen_foto"
    t.integer "filtro_pcv"
    t.text "filtro_pcv_observacion"
    t.text "filtro_pcv_foto"
    t.integer "valvula_pcv"
    t.text "valvula_pcv_observacion"
    t.text "valvula_pcv_foto"
    t.integer "bujias_encendido"
    t.text "bujias_encendido_observacion"
    t.text "bujias_encendido_foto"
    t.integer "cables_bujias_bobinas_ignicion"
    t.text "cables_bujias_bobinas_ignicion_observacion"
    t.text "cables_bujias_bobinas_ignicion_foto"
    t.integer "nivel_anticongenlante"
    t.text "nivel_anticongenlante_observacion"
    t.text "nivel_anticongenlante_foto"
    t.integer "tapon_radiador"
    t.text "tapon_radiador_observacion"
    t.text "tapon_radiador_foto"
    t.integer "mangueras_sistema"
    t.text "mangueras_sistema_observacion"
    t.text "mangueras_sistema_foto"
    t.integer "desempeño_ventilador"
    t.text "desempeño_ventilador_observacion"
    t.text "desempeño_ventilador_foto"
    t.integer "calidad_liquido_limpiaparabrisas"
    t.text "calidad_liquido_limpiaparabrisas_observacion"
    t.text "calidad_liquido_limpiaparabrisas_foto"
    t.integer "calidad_aceite_direccion_hidraulica"
    t.text "calidad_aceite_direccion_hidraulica_observacion"
    t.text "calidad_aceite_direccion_hidraulica_foto"
    t.integer "calidad_aceite_transmision_bayoneta"
    t.text "calidad_aceite_transmision_bayoneta_observacion"
    t.text "calidad_aceite_transmision_bayoneta_foto"
    t.integer "liquido_bateria_condiciones"
    t.text "liquido_bateria_condiciones_observacion"
    t.text "liquido_bateria_condiciones_foto"
    t.integer "bandas_poly_v"
    t.text "bandas_poly_v_observacion"
    t.text "bandas_poly_v_foto"
    t.integer "poleas_banda"
    t.text "poleas_banda_observacion"
    t.text "poleas_banda_foto"
    t.integer "banda_tiempo"
    t.text "banda_tiempo_observacion"
    t.text "banda_tiempo_foto"
    t.integer "otros_habitaculo_motor"
    t.text "otros_habitaculo_motor_observacion"
    t.text "otros_habitaculo_motor_foto"
    t.integer "reset_intervalo_servicio"
    t.text "reset_intervalo_servicio_observacion"
    t.text "reset_intervalo_servicio_foto"
    t.integer "ajuste_tornillos_neumaticos_torquimetro"
    t.text "ajuste_tornillos_neumaticos_torquimetro_observacion"
    t.text "ajuste_tornillos_neumaticos_torquimetro_foto"
    t.integer "limpiar_libricar_puertas_cerraduras"
    t.text "limpiar_libricar_puertas_cerraduras_observacion"
    t.text "limpiar_libricar_puertas_cerraduras_foto"
    t.integer "completar_plan_mantenimiento"
    t.text "completar_plan_mantenimiento_observacion"
    t.text "completar_plan_mantenimiento_foto"
    t.text "NumeroSerie"
    t.integer "id_checklist"
    t.string "TiempoTranscurrido", limit: 50
    t.integer "Activo"
  end

  create_table "clientes", force: :cascade do |t|
    t.string "nombre"
    t.string "calle"
    t.string "colonia"
    t.string "ciudad"
    t.string "estado"
    t.string "tel"
    t.string "cel"
    t.string "email"
    t.string "rfc"
    t.string "autorizacion_ext"
    t.string "no_int"
    t.string "facturar_a"
    t.integer "id_empleado"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "clientev2s", force: :cascade do |t|
    t.string "nombre"
    t.string "calle"
    t.string "colonia"
    t.string "ciudad"
    t.string "estado"
    t.string "tel"
    t.string "cel"
    t.string "email"
    t.string "rfc"
    t.string "autorizacion_ext"
    t.string "no_int"
    t.string "facturar_a"
    t.integer "id_empleado"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "empleados", force: :cascade do |t|
    t.string "nombre"
    t.string "rol"
    t.string "estatus"
    t.integer "id_usuario"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "empleadov2s", force: :cascade do |t|
    t.string "nombre"
    t.string "rol"
    t.string "estatus"
    t.integer "id_usuario"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "flotillav2s", force: :cascade do |t|
    t.string "namesflotillas"
    t.string "encargado"
    t.integer "id_flotilla"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "vehiculo_v2s", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "vehiculos_v2", force: :cascade do |t|
    t.string "marca"
    t.string "modelo"
    t.string "color"
    t.string "no_serie"
    t.string "placa"
    t.string "tipo"
    t.string "motor"
    t.integer "kms"
    t.boolean "espejo_retrovisor"
    t.boolean "espejo_izquierdo"
    t.boolean "espejo_derecho"
    t.boolean "antena"
    t.boolean "tapones_ruedas"
    t.boolean "radio"
    t.boolean "encendedor"
    t.boolean "gato"
    t.boolean "herramienta"
    t.boolean "llanta_refaccion"
    t.boolean "limpiadores"
    t.boolean "pintura_rayada"
    t.boolean "cristales_rotos"
    t.boolean "golpes"
    t.boolean "tapetes"
    t.boolean "extintor"
    t.boolean "tapones_gasolina"
    t.boolean "calaveras_rotas"
    t.boolean "molduras_completas"
    t.integer "id_cliente"
    t.integer "id_empleado"
    t.text "foto"
    t.text "espejo_retrovisor_foto"
    t.text "espejo_izquierdo_foto"
    t.text "antena_foto"
    t.text "tapones_ruedas_foto"
    t.text "radio_foto"
    t.text "encendedor_foto"
    t.text "gato_foto"
    t.text "herramienta_foto"
    t.text "llanta_refaccion_foto"
    t.text "limpiadores_foto"
    t.text "pintura_rayada_foto"
    t.text "cristales_rotos_foto"
    t.text "golpes_foto"
    t.text "tapetes_foto"
    t.text "extintor_foto"
    t.text "tapones_gasolina_foto"
    t.text "calaveras_rotas_foto"
    t.text "molduras_completas_foto"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_foreign_key "Vehiculos", "Vehiculos", column: "ID", primary_key: "ID", name: "FK_Vehiculos_Vehiculos"
end
