class CreateVehiculos < ActiveRecord::Migration[7.1]
  def change
    create_table :vehiculos do |t|
      t.integer :Id_Empleado
      t.string :Marca
      t.string :Modelo
      t.string :Color
      t.string :No_serie
      t.string :Placa
      t.string :Tipo
      t.string :Motor
      t.string :Kms
      t.integer :MotorVehiculo
      t.integer :Acumulador
      t.integer :Espejo_retrovisor
      t.integer :Espejo_izquierdo
      t.integer :Espejo_derecho
      t.integer :Antena
      t.integer :Tapones_ruedas
      t.integer :Radio
      t.integer :Encendedor
      t.integer :Gato
      t.integer :Herramienta
      t.integer :Llanta_refaccion
      t.integer :Limpiadores
      t.integer :Pintura_rayada
      t.integer :Cristales_rotos
      t.integer :Golpes
      t.integer :Tapetes
      t.integer :Extintor
      t.integer :Tapones_gasolina
      t.integer :Calaveras_rotas
      t.integer :Molduras_completas
      t.integer :Panel_instrumentos
      t.integer :Lado_izquierdo
      t.integer :Lado_izquierdo_inf
      t.integer :Lado_derecho
      t.integer :Lado_derecho_inf
      t.integer :Tablero
      t.integer :Guantera
      t.integer :Consola
      t.text :MotorVehiculo_foto
      t.text :Acumulador_foto
      t.text :Espejo_retrovisor_foto
      t.text :Espejo_izquierdo_foto
      t.text :Espejo_derecho_foto
      t.text :Antena_foto
      t.text :Tapones_ruedas_foto
      t.text :Radio_foto
      t.text :Encendedor_foto
      t.text :Gato_foto
      t.text :Herramienta_foto
      t.text :Llanta_refaccion_foto
      t.text :Limpiadores_foto
      t.text :Pintura_rayada_foto
      t.text :Cristales_rotos_foto
      t.text :Golpes_foto
      t.text :Tapetes_foto
      t.text :Extintor_foto
      t.text :Tapones_gasolina_foto
      t.text :Calaveras_rotas_foto
      t.text :Molduras_completas_foto
      t.text :Panel_instrumentos_foto
      t.text :Lado_izquierdo_foto
      t.text :Lado_izquierdo_inf_foto
      t.text :Lado_derecho_foto
      t.text :Lado_derecho_inf_foto
      t.text :Tablero_foto
      t.text :Guantera_foto
      t.text :Consola_foto
      t.text :MotorVehiculo_video
      t.text :Acumulador_video
      t.text :Espejo_retrovisor_video
      t.text :Espejo_izquierdo_video
      t.text :Espejo_derecho_video
      t.text :Antena_video
      t.text :Tapones_ruedas_video
      t.text :Radio_video
      t.text :Encendedor_video
      t.text :Gato_video
      t.text :Herramienta_video
      t.text :Llanta_refaccion_video
      t.text :Limpiadores_video
      t.text :Pintura_rayada_video
      t.text :Cristales_rotos_video
      t.text :Golpes_video
      t.text :Tapetes_video
      t.text :Extintor_video
      t.text :Tapones_gasolina_video
      t.text :Calaveras_rotas_video
      t.text :Molduras_completas_video
      t.text :Panel_instrumentos_video
      t.text :Lado_izquierdo_video
      t.text :Lado_izquierdo_inf_video
      t.text :Lado_derecho_video
      t.text :Lado_derecho_inf_video
      t.text :Tablero_video
      t.text :Guantera_video
      t.text :Consola_video
      t.integer :IdFlotilla
      t.integer :IdOrdenServicio
      t.integer :Activo

      t.timestamps
    end
  end
end
