class CreateVehiculov2s < ActiveRecord::Migration[8.0]
  def change
    create_table :vehiculov2s do |t|
      t.integer :Id_Empleado
      t.string :Marca
      t.string :Modelo
      t.string :Color
      t.string :No_serie
      t.string :Placa
      t.string :Tipo
      t.string :Motor
      t.string :Kms
      t.integer :MotorVehiculo
      t.integer :Acumulador
      t.integer :Espejo_retrovisor
      t.integer :Espejo_izquierdo
      t.integer :Espejo_derecho
      t.integer :Antena
      t.integer :Tapones_ruedas
      t.integer :Radio
      t.integer :Encendedor
      t.integer :Gato
      t.integer :Herramienta
      t.integer :Llanta_refaccion
      t.integer :Limpiadores
      t.integer :Pintura_rayada
      t.integer :Cristales_rotos
      t.integer :Golpes
      t.integer :Tapetes
      t.integer :Extintor
      t.integer :Tapones_gasolina
      t.integer :Calaveras_rotas
      t.integer :Molduras_completas
      t.integer :Panel_instrumentos
      t.integer :Lado_izquierdo
      t.integer :Lado_izquierdo_inf
      t.integer :Lado_derecho
      t.integer :Lado_derecho_inf
      t.integer :Tablero
      t.integer :Guantera
      t.integer :Consola
      t.string :MotorVehiculo_foto
      t.string :Acumulador_foto
      t.string :Espejo_retrovisor_foto
      t.string :Espejo_izquierdo_foto
      t.string :Espejo_derecho_foto
      t.string :Antena_foto
      t.string :Tapones_ruedas_foto
      t.string :Radio_foto
      t.string :Encendedor_foto
      t.string :Gato_foto
      t.string :Herramienta_foto
      t.string :Llanta_refaccion_foto
      t.string :Limpiadores_foto
      t.string :Pintura_rayada_foto
      t.string :Cristales_rotos_foto
      t.string :Golpes_foto
      t.string :Tapetes_foto
      t.string :Extintor_foto
      t.string :Tapones_gasolina_foto
      t.string :Calaveras_rotas_foto
      t.string :Molduras_completas_foto
      t.string :Panel_instrumentos_foto
      t.string :Lado_izquierdo_foto
      t.string :Lado_izquierdo_inf_foto
      t.string :Lado_derecho_foto
      t.string :Lado_derecho_inf_foto
      t.string :Tablero_foto
      t.string :Guantera_foto
      t.string :Consola_foto
      t.string :MotorVehiculo_video
      t.string :Acumulador_video
      t.string :Espejo_retrovisor_video
      t.string :Espejo_izquierdo_video
      t.string :Espejo_derecho_video
      t.string :Antena_video
      t.string :Tapones_ruedas_video
      t.string :Radio_video
      t.string :Encendedor_video
      t.string :Gato_video
      t.string :Herramienta_video
      t.string :Llanta_refaccion_video
      t.string :Limpiadores_video
      t.string :Pintura_rayada_video
      t.string :Cristales_rotos_video
      t.string :Golpes_video
      t.string :Tapetes_video
      t.string :Extintor_video
      t.string :Tapones_gasolina_video
      t.string :Calaveras_rotas_video
      t.string :Molduras_completas_video
      t.string :Panel_instrumentos_video
      t.string :Lado_izquierdo_video
      t.string :Lado_izquierdo_inf_video
      t.string :Lado_derecho_video
      t.string :Lado_derecho_inf_video
      t.string :Tablero_video
      t.string :Guantera_video
      t.string :Consola_video
      t.integer :IdFlotilla
      t.integer :IdOrdenServicio
      t.integer :Activo

      t.timestamps
    end
  end
end
